CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(30) NOT NULL,
  password VARCHAR(30) NOT NULL,
  email VARCHAR(100) NOT NULL,
  birthday DATETIME NOT NULL,
  PRIMARY KEY (id), UNIQUE (username, email)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
